# Generated by Django 4.1.6 on 2023-03-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=str, max_digits=10),
        ),
    ]
