# Generated by Django 4.1.6 on 2023-03-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image', verbose_name='изображение')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='название')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='номер телефона')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='имейл')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='пароль')),
                ('new_passeord', models.CharField(blank=True, max_length=50, null=True, verbose_name='новый_пароль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='files/', verbose_name='изображение')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=500, verbose_name='описание')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200)),
                ('blog', models.CharField(choices=[('notebook', 'notebook'), ('lightings', 'lightings'), ('clothings', 'clothings'), ('furniture', 'furniture'), ('trends', 'trends'), ('pk', 'pk'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('more', 'more'), ('bags', 'bags'), ('cameras', 'cameras')], default='mobile', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorys', to='work_django.category')),
            ],
            options={
                'ordering': ('title',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('text', models.TextField(max_length=2500, verbose_name='текст')),
                ('email', models.EmailField(max_length=50, verbose_name='имейл')),
                ('creat_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='work_django.product')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
