# Generated by Django 4.1.6 on 2023-03-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registermodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('notebook', 'notebook'), ('bags', 'bags'), ('lightings', 'lightings'), ('cameras', 'cameras'), ('pk', 'pk'), ('clothings', 'clothings'), ('accessories', 'accessories'), ('more', 'more'), ('furniture', 'furniture'), ('mobile', 'mobile'), ('trends', 'trends')], default='mobile', max_length=50),
        ),
    ]
