# Generated by Django 4.1.6 on 2023-03-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0002_remove_registermodel_email_alter_product_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('clothings', 'clothings'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('trends', 'trends'), ('bags', 'bags'), ('furniture', 'furniture'), ('lightings', 'lightings'), ('mobile', 'mobile'), ('cameras', 'cameras'), ('more', 'more'), ('pk', 'pk')], default='mobile', max_length=50),
        ),
    ]
