# Generated by Django 4.1.6 on 2023-03-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0004_alter_product_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='limited_edition',
            field=models.BooleanField(default=True, verbose_name='Ограниченный тираж'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('more', 'more'), ('pk', 'pk'), ('cameras', 'cameras'), ('bags', 'bags'), ('trends', 'trends'), ('notebook', 'notebook'), ('furniture', 'furniture'), ('mobile', 'mobile'), ('clothings', 'clothings'), ('accessories', 'accessories'), ('lightings', 'lightings')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
