# Generated by Django 4.1.6 on 2023-03-11 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0005_product_limited_edition_alter_product_blog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('notebook', 'notebook'), ('more', 'more'), ('bags', 'bags'), ('pk', 'pk'), ('cameras', 'cameras'), ('furniture', 'furniture'), ('accessories', 'accessories'), ('clothings', 'clothings'), ('lightings', 'lightings'), ('mobile', 'mobile'), ('trends', 'trends')], default='mobile', max_length=50),
        ),
    ]
