# Generated by Django 4.1.6 on 2023-03-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0006_product_discount_alter_product_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('mobile', 'mobile'), ('more', 'more'), ('lightings', 'lightings'), ('cameras', 'cameras'), ('clothings', 'clothings'), ('pk', 'pk'), ('trends', 'trends'), ('furniture', 'furniture'), ('accessories', 'accessories'), ('bags', 'bags'), ('notebook', 'notebook')], default='mobile', max_length=50),
        ),
    ]
