# Generated by Django 4.1.6 on 2023-03-12 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0008_alter_product_blog_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_time',
            field=models.DateTimeField(blank=True, null=True, unique_for_date=True, unique_for_month=True, verbose_name='дата скидки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('cameras', 'cameras'), ('mobile', 'mobile'), ('lightings', 'lightings'), ('notebook', 'notebook'), ('pk', 'pk'), ('furniture', 'furniture'), ('accessories', 'accessories'), ('trends', 'trends'), ('bags', 'bags'), ('more', 'more'), ('clothings', 'clothings')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
