# Generated by Django 4.1.6 on 2023-03-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0009_product_discount_time_alter_product_blog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('pk', 'pk'), ('mobile', 'mobile'), ('lightings', 'lightings'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('bags', 'bags'), ('clothings', 'clothings'), ('furniture', 'furniture'), ('cameras', 'cameras'), ('more', 'more'), ('trends', 'trends')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_time',
            field=models.DateTimeField(blank=True, null=True, unique_for_month=True, verbose_name='дата скидки'),
        ),
    ]
