# Generated by Django 4.1.6 on 2023-03-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0010_alter_product_blog_alter_product_discount_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('furniture', 'furniture'), ('more', 'more'), ('notebook', 'notebook'), ('lightings', 'lightings'), ('mobile', 'mobile'), ('clothings', 'clothings'), ('pk', 'pk'), ('accessories', 'accessories'), ('trends', 'trends'), ('cameras', 'cameras'), ('bags', 'bags')], default='mobile', max_length=50),
        ),
    ]
