# Generated by Django 4.1.6 on 2023-03-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0011_remove_product_discount_time_alter_product_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_from',
            field=models.DateTimeField(null=True, verbose_name='скидка с'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_to',
            field=models.DateTimeField(null=True, verbose_name='скидка до'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('more', 'more'), ('furniture', 'furniture'), ('cameras', 'cameras'), ('pk', 'pk'), ('mobile', 'mobile'), ('trends', 'trends'), ('bags', 'bags'), ('lightings', 'lightings'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('clothings', 'clothings')], default='mobile', max_length=50),
        ),
    ]
