# Generated by Django 4.1.6 on 2023-03-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0012_product_discount_from_product_discount_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('bags', 'bags'), ('cameras', 'cameras'), ('trends', 'trends'), ('more', 'more'), ('clothings', 'clothings'), ('furniture', 'furniture'), ('pk', 'pk'), ('mobile', 'mobile'), ('accessories', 'accessories'), ('notebook', 'notebook'), ('lightings', 'lightings')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='скидка с'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_to',
            field=models.DateTimeField(blank=True, null=True, verbose_name='скидка до'),
        ),
    ]
