# Generated by Django 4.1.6 on 2023-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0013_alter_product_blog_alter_product_discount_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('accessories', 'accessories'), ('furniture', 'furniture'), ('lightings', 'lightings'), ('trends', 'trends'), ('bags', 'bags'), ('clothings', 'clothings'), ('pk', 'pk'), ('cameras', 'cameras'), ('notebook', 'notebook'), ('mobile', 'mobile'), ('more', 'more')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
