# Generated by Django 4.1.6 on 2023-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0014_alter_product_blog_alter_product_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('lightings', 'lightings'), ('mobile', 'mobile'), ('cameras', 'cameras'), ('more', 'more'), ('furniture', 'furniture'), ('notebook', 'notebook'), ('accessories', 'accessories'), ('clothings', 'clothings'), ('trends', 'trends'), ('pk', 'pk'), ('bags', 'bags')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_from',
            field=models.DateField(blank=True, null=True, verbose_name='скидка с'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_to',
            field=models.DateField(blank=True, null=True, verbose_name='скидка до'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
