# Generated by Django 4.1.6 on 2023-03-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0015_alter_product_blog_alter_product_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True, verbose_name='скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('trends', 'trends'), ('mobile', 'mobile'), ('pk', 'pk'), ('lightings', 'lightings'), ('more', 'more'), ('furniture', 'furniture'), ('notebook', 'notebook'), ('clothings', 'clothings'), ('bags', 'bags'), ('accessories', 'accessories'), ('cameras', 'cameras')], default='mobile', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_django.product')),
            ],
        ),
    ]
