# Generated by Django 4.1.6 on 2023-03-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0016_remove_product_discount_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('notebook', 'notebook'), ('bags', 'bags'), ('more', 'more'), ('accessories', 'accessories'), ('pk', 'pk'), ('cameras', 'cameras'), ('clothings', 'clothings'), ('mobile', 'mobile'), ('trends', 'trends'), ('furniture', 'furniture'), ('lightings', 'lightings')], default='mobile', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='скидка в процентах'),
        ),
    ]
