# Generated by Django 4.1.6 on 2023-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0018_alter_product_blog_delete_productitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('mobile', 'mobile'), ('cameras', 'cameras'), ('accessories', 'accessories'), ('clothings', 'clothings'), ('notebook', 'notebook'), ('furniture', 'furniture'), ('more', 'more'), ('bags', 'bags'), ('lightings', 'lightings'), ('pk', 'pk'), ('trends', 'trends')], default='mobile', max_length=50),
        ),
    ]
