# Generated by Django 4.1.6 on 2023-03-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_django', '0019_alter_product_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='blog',
            field=models.CharField(choices=[('clothings', 'clothings'), ('pk', 'pk'), ('more', 'more'), ('notebook', 'notebook'), ('furniture', 'furniture'), ('accessories', 'accessories'), ('bags', 'bags'), ('trends', 'trends'), ('cameras', 'cameras'), ('lightings', 'lightings'), ('mobile', 'mobile')], default='mobile', max_length=50),
        ),
    ]
